language: generic   #specifies the language to display output
sudo: required      #establish sudo privilage when travis is working for us
services:
  - docker          #require docker engine
before_install: 
  - docker build -t chuk05/react-test:latest -f ./client/Dockerfile.dev ./client  #tell travis to build the image first and to use Dockerfile when deploying which is standard
script:
  - docker run -e CI=true chuk05/react-test npm test # https://create-react-app.dev/docs/running-tests/#linux-macos-bash
after_success: 
  - docker build -t chuk05/multi-client ./client
  - docker build -t chuk05/multi-ngnix ./nginx
  - docker build -t chuk05/multi-server ./server
  - docker build -t chuk05/multi-worker ./worker
# log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take above images and push them to docker hub
  - docker push chuk05/multi-client
  - docker push chuk05/multi-ngnix 
  - docker push chuk05/multi-server
  - docker push chuk05/multi-worker
deploy:
  provider: elasticbeanstalk
  # user settings/Enviromental variables/*add* access_key_id and then secret_access_key to define your secrets
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  # env_name ends
  bucket: "elasticbeanstalk-us-east-1-889306573262"
  bucket_path: "docker"
  edge: true # opt in to dpl v2
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  on:
    branch: master
