services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis: 
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ~/fabonachi-sql-redis-worker/server:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ~/fabonachi-sql-redis-worker/client:/home/node/app
    environment:
      #Fixes bug where websocket connection is fixed to default port 3000
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /home/node/app/node_modules
      - ~/fabonachi-sql-redis-worker/worker:/home/node/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379